Добавить проект с пустой активити
blotterp/65apps pull request #1
Opened 2021-10-05 16:34 UTC by blotterp

2021-10-05 17:54 UTC, goblinr requested changes

2021-10-05 17:54 UTC, goblinr commented on app/build.gradle
> +        applicationId "com.example.androidapp"
Давайте сразу определим `applicationId` который будет строиться от вашей почты, т.е. если ваша почта: `example@gmail.com` то этот `applicationId` - валидный, но я думаю что ваша почта отличается.

2021-10-05 17:54 UTC, goblinr commented on app/src/androidTest/java/com/example/androidapp/ExampleInstrumentedTest.kt
> +package com.example.androidapp
Соответственно и package name нужно будет изменить.

2021-10-06 15:58 UTC, goblinr commented on app/build.gradle
> +        minSdkVersion 26
`minSdkVersion` ставим `21`

2021-10-12 14:20 UTC, blotterp commented
@goblinr исправлено

2021-10-12 14:23 UTC, goblinr commented
Вы точно исправили? Я не вижу изменений по `minSdkVersion`.

2021-10-12 14:28 UTC, blotterp commented
> Вы точно исправили? Я не вижу изменений по `minSdkVersion`.

Теперь точно

2021-10-12 14:57 UTC, sashawhm commented
принял

2021-10-12 14:57 UTC, merged